# Generated by Django 2.2.6 on 2019-10-15 17:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='member',
            field=models.ManyToManyField(blank=True, through='groups.GroupMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
